//------------------------------------------------------------------------
// Copyright(c) 2024 ArtificialVoid1.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"OD-1.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"OD-1 VST3 (64Bit)"
#else
#define stringFileDescription	"OD-1 VST3"
#endif
#define stringCompanyName		"ArtificialVoid1\0"
#define stringLegalCopyright	"Copyright(c) 2024 ArtificialVoid1."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
